name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  deploy:
    runs-on: amazon-linux-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.5  # Specify the desired Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust the region as needed

      - name: Initialize Terraform
        run: |
          terraform init
          terraform --version  # Display Terraform version for debugging

      - name: Initialize Terraform
        run: |
          terraform init
          terraform --version  # Display Terraform version for debugging
          echo ls -l
