name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.5  # Specify the desired Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust the region as needed

      - name: Initialize Terraform
        run: |
          terraform init
          terraform --version  # Display Terraform version for debugging

      - name: Install AWS CLI
        run: |
          set -eux
          cd "$(mktemp -d)"
          curl -sf "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version


      # - name: Configure AWS CLI
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && \
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && \
      #     aws configure set region us-east-1


      - name: Configure AWS CLI
        run: |
          printf "aws configure set aws_access_key_id %s\\n" "${{ secrets.AWS_ACCESS_KEY_ID }}" >> configure_script.sh &&
          printf "aws configure set aws_secret_access_key %s\\n" "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> configure_script.sh &&
          printf "aws configure set region us-east-1\\n" >> configure_script.sh &&
          bash configure_script.sh

      # - name: Configure AWS CLI
      #   run: |
      #     cat <<EOF > configure_script.sh
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set region us-east-1
      #     EOF
      #     bash configure_script.sh

      - name: AWS CLI Check 
        run: |
          aws configure list
          terraform --version  # Display Terraform version for debugging

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # - name: Set KUBECONFIG
      #   run: echo "::set-env name=KUBECONFIG::/home/runner/.kube/config"

      # - name: test KUBECONFIG
      #   run: ls /home/runner/.kube/config          

      - name: Terraform apply
        run: terraform plan -var="tenant_name=opstra"

      #    # On push to "main", build or change infrastructure according to Terraform configuration files
      #    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      #   run: terraform apply  -var="tenant_name=opstra" -auto-approve
